### ISSUE TITLE
naturaldelta rounds down the months

### ISSUE THREAD

**Issue by Maiakel** [jmoiron/humanize#116]
this should be 5 months
```py
>> import humanize
>> humanize.naturaldelta(13140015)
'4 months'
```

**Comment by hugovk** [comment]
Thanks for the report. 

13140015 is 2019-09-25 07:36:15.471987, which right now is 152 days ago.

This is the relevant part of the code:

```python
    months = int(days // 30.5)
```

Which works out like:
```pycon
>>> 152 / 30.5
4.983606557377049
>>> 152 // 30.5
4.0
>>> int(152 // 30.5)
4
```

So it's rounding down, to report the number of full months that has elapsed.

**Comment by luisgc93** [comment]
I was about to open this same issue.

> So it's rounding down, to report the number of full months that has elpased.

To me this doesn't seem like a very "human" approach.

Say you have two dates: 

`date_1 = datetime.date(2020, 12, 13)`
`date_2 = datetime.date(2021, 3, 13)`

A human would say that the time difference is 3 months. However, since the time difference is 90 days, these are rounded down to 2 months.
