### ISSUE TITLE
Unit abbreviations for intword: print '22k' instead of '22 thousand'

### ISSUE THREAD

**Issue by OlexiyO** [jmoiron/humanize#160]
Good day,

In some contexts, a human-friendly version of numbers might include abbreviations for units (like 'k', 'M', 'G', etc).
While humanize provides a special version for file sizes (and distances are pending), many other areas are not covered:

* Prices: instead of '$3.10 million', print '$3.10M'
* Scientific units: '100kPA' for pressure; '3kW'
and so on.

Would it be possible to answer the following questions:
1. Would the owners of the `humanize` mind if I added this functionality?

2. If the feature seems acceptable, what would be the preferred API to provide access to it?
I could see at least a few ways: 

* Add a new method `intchar(value, format)`.
In this case, the code would look like
```python
intchar(3120123, format='$%.1f') --> '$3.1M'
intchar(22123, format='%.1fB') --> '22.0kB'
```

* Add a parameter to `intword(value, format="%.1f", abbreviated_units=False)`

Thank you!

**Comment by hugovk** [comment]
Hello!

Sounds useful. I'd suggest extending `intword`.

I wonder, rather than adding a Boolean flag, might there be a need in the future for a third or fourth set of endings? For example, now we have "million", and are adding (I presume scientific) "M". Might there be a non-scientific set including, maybe, "m"? Or long-scale/short-scale ("billion" v. "milliard")?

If so, we wouldn't need to add more than the two you suggest right now. What would be a good name? Maybe "suffix" or something else?

Another idea is using a special locale for abbreviated English output, for example see https://github.com/jmoiron/humanize/pull/73.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues

And https://github.com/python-humanize/humanize/pull/1 might address this?
