### ISSUE TITLE
Incorrect precisedelta() calcualation

### ISSUE THREAD

**Issue by mierzwin** [jmoiron/humanize#220]
### What did you do?

I wanted to convert the time delta into a human-readable format. 

### What did you expect to happen?

Count months and days.

### What actually happened?

Days were counted wrong by a factor of 2.

### What versions are you using?

* OS: Windows 10
* Python: 3.8
* Humanize: 3.10.0

```python
import humanize
from dateutil.parser import parse

base_date = parse('27/07/2021').date()
change_date = parse('2020-12-14T00:00:00').date()

print(base_date)
print(change_date)
print(humanize.precisedelta(base_date-change_date))
```

```  
2021-07-27
2020-12-14
7 months and 11 days
```

**Comment by hugovk** [comment]
> Days were counted wrong by a factor of 2.

Do you mean the result was wrong by 2 days?

Were you expecting 7 months and 13 days?

**Comment by mierzwin** [comment]
> > Days were counted wrong by a factor of 2.
> 
> Do you mean the result was wrong by 2 days?
> 
> Were you expecting 7 months and 13 days?

Yes indeed. If you look at the dates above they are start from 14-12-2020 and the end of 27-07-2021.

December to July is 7 months and 14th to 27th is 13 days.

**Comment by hugovk** [comment]
@eldipa Please could you have a look at this? Thank you!

**Comment by eldipa** [comment]
Hi, I think it is not a bug but a limitation of the knowledge that `precisedelta` has.

`precisedelta` receives a `timedelta` object from the result of `base_date-change_date` which Python correctly computes to `timedelta(days=225)`.

This is possible because `base_date` and `change_date` are two `date` objects so Python can know exactly *which* months are between the two dates and then compute the exactly amount of days.

Doing it by hand you will have:
```
January + March + May -> 31 * 3 days
April + June -> 30 * 3 days
February -> 28 days
```

Adding those plus the extra days that you have in December (`31-14`) and the days of July (`27`), the result is:

```python
>>> 31*3 + 30*2 +  28 + (31 - 14) + 27
225
```

So far, so good. But now, let's see this from the point of view of `precisedelta`.

It receives `timedelta(days=225)`. *Which* months contributed to that delta? `precisedelta` cannot know, simply there is not enough information.

Instead, `precisedelta` *assumes* `30.5` days per month so it computes `225//30.5 == 7` months and `225%30.5 == 11.5` days.

That's why you are seeing `11` days instead of `13` days.

Note how you found correctly `13` because you *know* that there are 7 months between the two dates: January, February, ..., July. July is not a complete month so you need to take from the days in December (`31-14 == 17`) `4` days to complete July remaining `31-14-4==13` days.

I don't think we can improve `precisedelta` with just a delta of time.

@hugovk, @mierzwin , what are your thoughts?

**Comment by hugovk** [comment]
@eldipa Thank you for the explanation, I agree it's not a bug and `precisedelta` is doing the best with the input it receives, a `timedelta`, as described in the docstring:

> Return a precise representation of a timedelta.

And it has no knowledge of _which_ months are in the delta.

**Comment by hugovk** [comment]
🚀 Development has moved to https://github.com/python-humanize/humanize 🚀

Please open new issues at https://github.com/python-humanize/humanize/issues
