### ISSUE TITLE
The package (wrongly) assumes all times are in the local timezone

### ISSUE THREAD

**Issue by JanLikar** [jmoiron/humanize#55]

**Comment by shaleh** [comment]
Can you provide example failures and expected results?

**Comment by kippandrew** [comment]
The issue seems to be the `naturaltime` function (and possibly others) assumes that a `datetime` object that is passed is timezone naive (meaning it has no tzinfo). If you do pass a timezone aware datetime, an error is raised because you can't compare a timezone naive and timezone aware datetime object. 

A solution might be to allow the caller to pass in the 'now' time. 

On Python 3.5:
```
>>> import datetime
>>> import humanize

# parse a timestamp with utc offset
>>> ts = datetime.datetime.strptime("2018-02-15T21:31:16.048820-0800", "%Y-%m-%dT%H:%M:%S.%f%z")

>>> ts
datetime.datetime(2018, 2, 15, 21, 31, 16, 48820, tzinfo=datetime.timezone(datetime.timedelta(-1, 57600)))

>>> humanize.naturaltime(ts)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Users/akipp/.virtualenvs/lucid-kube/lib/python3.5/site-packages/humanize/time.py", line 116, in naturaltime
    date, delta = date_and_delta(value)
  File "/Users/akipp/.virtualenvs/lucid-kube/lib/python3.5/site-packages/humanize/time.py", line 30, in date_and_delta
    delta = now - value
TypeError: can't subtract offset-naive and offset-aware datetimes```

**Comment by kippandrew** [comment]
Another solution would be to allow the caller to pass in tzinfo struct and localize the "now" time to that tz.
